# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: '#about'
    weight: 1
  - name: Skills
    url: '#skills'
    weight: 2
  - name: Accomplishments
    url: '#accomplishments'
    weight: 3
  - name: Developments
    url: '#developments'
    weight: 4
  - name: Experience
    url: '#experience'
    weight: 5
  - name: Awards
    url: '#awards'
    weight: 6
  - name: Grants
    url: '#grants'
    weight: 7
  - name: Publications
    url: '#articles'
    weight: 8
  - name: Talks
    url: '#talks'
    weight: 11
  - name: Contact
    url: '#contact'
    weight: 13
